"""Generate a synthetic Open-Close file so the workflow can be rehearsed.

Buying Cboe data is a decision; learning what the commands do should not be.
This writes files shaped like an exchange Open-Close summary so an operator can
walk `inspect-cboe` → `check-load` → `reconstruct` end to end, see what each
command prints, and know what "good" looks like before spending anything.

**The column names here are invented, and so are the numbers.**  The real Cboe
header will differ — that is precisely why `inspect-cboe` exists and why a
profile must be human-confirmed before it loads.  Do not treat this file as a
specification of Cboe's format, and never treat anything computed from it as a
finding.  Every file written carries a ``SYNTHETIC`` prefix and the directory
gets a README saying the same thing.

The generator deliberately builds a mix the diagnostics can distinguish:

* some series trade from the first session (left-censored — their inventory
  cannot be built from a known zero),
* some appear mid-window (cleanly reconstructable),
* every Market Maker bucket is mirrored by an opposite-side Customer bucket, so
  the zero-sum check passes and the open-interest identity is coherent.

Run ``reconstruct`` against it and you should see a partial ``clean_share`` —
which is the honest shape of a short window, and the thing to compare a real
delivery against.
"""

from __future__ import annotations

import csv
from datetime import date, datetime, time, timedelta
from pathlib import Path
from typing import Any, Iterator, Optional, Sequence

import numpy as np

from src.market_calendar import load_nyse_holidays

__all__ = ["SAMPLE_HEADER", "write_sample_files", "sample_rows"]

_PARTICIPANTS = (
    "market_maker",
    "customer",
    "professional_customer",
    "broker_dealer",
    "firm",
)
_EFFECTS = ("open", "close")
_SIDES = ("buy", "sell")

#: Invented header, in the wide shape exchange Open-Close summaries use.
SAMPLE_HEADER: tuple[str, ...] = (
    "underlying_symbol",
    "option_root",
    "trade_date",
    "interval_end",
    "expiration",
    "strike",
    "call_put",
    *(
        f"{participant}_{effect}_{side}"
        for participant in _PARTICIPANTS
        for effect in _EFFECTS
        for side in _SIDES
    ),
)

_README = """\
SYNTHETIC DATA — NOT CBOE DATA, NOT MARKET DATA
===============================================

These files were generated by
`python -m research.mm_attributed_gex.cli make-sample` so the Market-Maker
Attributed GEX workflow can be rehearsed without purchasing anything.

  * The COLUMN NAMES are invented. A real Cboe Open-Close file will have a
    different header — that is why `inspect-cboe` proposes a mapping for a
    human to confirm rather than assuming one.
  * The NUMBERS are random. Nothing computed from these files says anything
    about markets, about Market-Maker Attributed GEX, or about whether the
    methodology works.

Use them to learn what each command prints and what a healthy reconstruction
looks like. Then delete them and run the same commands against real files.
"""


def _sessions(start: date, count: int) -> list[date]:
    """``count`` NYSE sessions starting at or after ``start``."""
    holidays = load_nyse_holidays()
    out: list[date] = []
    cursor = start
    while len(out) < count:
        if cursor.weekday() < 5 and cursor not in holidays:
            out.append(cursor)
        cursor += timedelta(days=1)
    return out


def _bucket_times(interval_minutes: int) -> list[time]:
    """Interval ends across an RTH session, 09:30–16:00 ET."""
    out: list[time] = []
    cursor = datetime(2000, 1, 1, 9, 30) + timedelta(minutes=interval_minutes)
    end = datetime(2000, 1, 1, 16, 0)
    while cursor <= end:
        out.append(cursor.time())
        cursor += timedelta(minutes=interval_minutes)
    return out


def sample_rows(
    *,
    sessions: Sequence[date],
    expirations: Sequence[date],
    strikes: Sequence[float],
    interval_minutes: int = 10,
    seed: int = 20260821,
    symbol: str = "SPX",
    option_root: str = "SPXW",
) -> Iterator[dict[str, Any]]:
    """Yield rows in :data:`SAMPLE_HEADER` order, one per (series, bucket).

    Market Maker volume is mirrored by an opposite-side Customer bucket so the
    zero-sum identity holds; a slice of strikes is withheld until partway
    through the window so the run contains both censored and cleanly
    reconstructable series.
    """
    rng = np.random.default_rng(seed)
    buckets = _bucket_times(interval_minutes)
    # Strikes in the back half of the list start trading partway through the
    # window, so their inventory genuinely begins from zero inside it and the
    # run contains both censored and cleanly reconstructable series.
    #
    # The start index adapts to the window length.  A fixed index silently
    # dropped those strikes entirely whenever the window was shorter than it —
    # which matters most for an ANCHORED run, where the strikes were chosen
    # because they exist in the database and half of them vanishing is the
    # opposite of what the caller asked for.
    late_start = set(list(strikes)[len(strikes) // 2 :])
    late_start_index = min(2, max(1, len(sessions) - 1))

    # Running MM inventory per series, so a closing bucket never retires more
    # than the position actually holds.  Drawing opens and closes independently
    # produces flow that cannot exist, and the reconstruction rightly reads it
    # as proof of pre-window inventory — which would censor every series and
    # teach the reader the opposite of what a healthy delivery looks like.
    held: dict[tuple, list[int]] = {}

    for session_index, session in enumerate(sessions):
        for bucket in buckets:
            for expiration in expirations:
                if expiration < session:
                    continue
                for strike in strikes:
                    if strike in late_start and session_index < late_start_index:
                        continue
                    for option_type in ("C", "P"):
                        row: dict[str, Any] = {
                            "underlying_symbol": symbol,
                            "option_root": option_root,
                            "trade_date": session.isoformat(),
                            "interval_end": bucket.strftime("%H:%M:%S"),
                            "expiration": expiration.isoformat(),
                            "strike": f"{strike:g}",
                            "call_put": option_type,
                        }
                        for column in SAMPLE_HEADER[7:]:
                            row[column] = 0
                        key = (expiration, strike, option_type)
                        position = held.setdefault(key, [0, 0])  # [long, short]
                        emitted = False

                        def _emit(effect: str, side: str, qty: int) -> None:
                            nonlocal emitted
                            if qty <= 0:
                                return
                            emitted = True
                            row[f"market_maker_{effect}_{side}"] = qty
                            # Mirror onto the customer leg with the opposite
                            # side, so every contract has a reported
                            # counterparty and the zero-sum check holds.
                            other = "sell" if side == "buy" else "buy"
                            row[f"customer_{effect}_{other}"] = (
                                int(row[f"customer_{effect}_{other}"]) + qty
                            )

                        open_buys = int(rng.integers(0, 40))
                        open_sells = int(rng.integers(0, 40))
                        _emit("open", "buy", open_buys)
                        _emit("open", "sell", open_sells)
                        position[0] += open_buys
                        position[1] += open_sells

                        # Close at most what is held.
                        close_sells = min(position[0], int(rng.integers(0, 30)))
                        close_buys = min(position[1], int(rng.integers(0, 30)))
                        _emit("close", "sell", close_sells)
                        _emit("close", "buy", close_buys)
                        position[0] -= close_sells
                        position[1] -= close_buys

                        if emitted:
                            yield row


def write_sample_files(
    out_dir: str | Path,
    *,
    n_sessions: int = 5,
    start: Optional[date] = None,
    interval_minutes: int = 10,
    seed: int = 20260821,
    sessions: Optional[Sequence[date]] = None,
    expirations: Optional[Sequence[date]] = None,
    strikes: Optional[Sequence[float]] = None,
    symbol: str = "SPX",
    option_root: str = "SPXW",
) -> list[Path]:
    """Write one CSV per session into ``out_dir``.  Returns the paths.

    One file per session matches how Open-Close data is normally delivered and
    exercises the loader's directory walk, which must consume files in
    chronological order.

    ``sessions`` / ``expirations`` / ``strikes`` override the invented defaults.
    Passing real ones (see
    :func:`research.mm_attributed_gex.sources.fetch_sample_anchor`) anchors the
    synthetic flow to contracts that exist in the database, which is what lets
    the dataset and backtest steps be rehearsed before any data is bought.  The
    flow is still invented either way.
    """
    directory = Path(out_dir)
    directory.mkdir(parents=True, exist_ok=True)

    # Clear this generator's own previous output.  Without it a second run —
    # re-generating with different sessions, or switching to --anchor-to-db —
    # leaves the earlier files in place, and the loader dutifully consumes
    # BOTH.  The result is one "delivery" spanning two unrelated windows with a
    # months-long hole in the middle, which is not a scenario any operator
    # meant to create.  Scoped to the SYNTHETIC_ prefix this generator writes,
    # so a directory holding real files alongside them is untouched.
    removed = 0
    for stale in sorted(directory.glob("SYNTHETIC_openclose_c1_*.csv")):
        stale.unlink()
        removed += 1
    if removed:
        print(f"  (removed {removed} file(s) from a previous sample run)")

    (directory / "README_SYNTHETIC.txt").write_text(_README, encoding="utf-8")

    if sessions is None:
        sessions = _sessions(start or date(2026, 6, 1), n_sessions)
    sessions = list(sessions)
    if expirations is None:
        # Two expirations: one inside the window (so contracts retire
        # mid-study) and one just after it.
        expirations = [sessions[-1], sessions[-1] + timedelta(days=7)]
    if strikes is None:
        strikes = [5900.0 + 25.0 * i for i in range(9)]

    by_session: dict[str, list[dict[str, Any]]] = {s.isoformat(): [] for s in sessions}
    for row in sample_rows(
        sessions=sessions,
        expirations=expirations,
        strikes=strikes,
        interval_minutes=interval_minutes,
        seed=seed,
        symbol=symbol,
        option_root=option_root,
    ):
        by_session[row["trade_date"]].append(row)

    written: list[Path] = []
    for session in sessions:
        path = directory / f"SYNTHETIC_openclose_c1_{session:%Y%m%d}.csv"
        with path.open("w", newline="", encoding="utf-8") as fh:
            writer = csv.DictWriter(fh, fieldnames=list(SAMPLE_HEADER))
            writer.writeheader()
            writer.writerows(by_session[session.isoformat()])
        written.append(path)
    return written
