"""The v2 freshness envelope — endpoint health, evaluation time and data age
as three separately machine-readable concepts.

Every ``/api/v2/*`` response is wrapped as::

    {"data": <the v1 payload, unchanged>, "freshness": {...}}

and the ``freshness`` block answers the questions a consumer previously had
to reverse-engineer from whichever ad-hoc ``timestamp`` field an endpoint
happened to carry:

``evaluated_at``
    When the API evaluated *this response*.  Server wall clock, always
    present.  This is an **endpoint-health** signal: it advances on every
    request even when the underlying data is frozen, so a client can tell
    "the API answered me just now" apart from "the data is current".

``generated_at``
    When the served data was *computed*.  For snapshot-backed endpoints
    (the ~60 s analytics cycle) this is the snapshot's own stamp; for
    endpoints computed on demand for this request it equals
    ``evaluated_at``.

``source_timestamp``
    The stamp of the upstream market data the payload is derived from —
    the quote/snapshot instant, not the compute instant.  This is the
    **data-freshness** signal, and the one ``freshness_status`` is
    computed against.

``latest_event_at``
    The newest event timestamp actually present in the payload.  For a
    time series this is the last bar/row; for a single snapshot it usually
    equals ``source_timestamp``.  Best-effort (see ``_scan_timestamps``).

``market_session_status``
    ``pre-market`` | ``regular`` | ``after-hours`` | ``closed`` — the same
    four-value taxonomy the ``session`` field on ``/api/market/quote``
    already uses, deliberately not a second competing vocabulary.

``expected_update_cadence`` / ``expected_update_cadence_seconds``
    How often this endpoint's data is expected to change *right now*, as
    an ISO-8601 duration and as a number.  Session-dependent: the
    analytics cycle is 60 s during the cash session and 300 s off-hours.
    ``null`` means **no updates are expected** (a weekend, a holiday, or a
    feed that only runs during the session) — the served value is the last
    good one, not a stalled one.

``stale_after``
    The instant after which this payload should be treated as stale.
    Published so a consumer can set its own timer instead of guessing a
    threshold.  ``null`` whenever ``expected_update_cadence`` is ``null``.

``freshness_status``
    The rolled-up verdict — see :class:`FreshnessStatus`.

Why the cadence is a registry rather than a per-handler argument: the v2
surface is generated by mirroring every v1 route (see ``src/api/v2.py``),
so cadence has to be resolvable from the request path alone.  The registry
below is the single place an operator changes when a feed's cadence
changes, and every entry cites the config constant it mirrors.
"""

from __future__ import annotations

import fnmatch
import logging
from collections import deque
from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone
from enum import Enum
from itertools import chain
from typing import Any, Deque, Generic, Iterable, Optional, Tuple, TypeVar

import pytz
from pydantic import BaseModel, Field

from src.config import (
    AGGREGATION_BUCKET_SECONDS,
    ANALYTICS_INTERVAL,
)

logger = logging.getLogger(__name__)

_ET = pytz.timezone("US/Eastern")


# ---------------------------------------------------------------------------
# Vocabularies
# ---------------------------------------------------------------------------

# Mirrors src/market_calendar.py::get_market_session and the ``session`` field
# already returned by /api/market/quote. Kept identical on purpose — a second
# session vocabulary inside the same API would be worse than none.
SESSION_PRE_MARKET = "pre-market"
SESSION_REGULAR = "regular"
SESSION_AFTER_HOURS = "after-hours"
SESSION_CLOSED = "closed"


class FreshnessStatus(str, Enum):
    """The rolled-up freshness verdict for one response.

    ``fresh``
        ``source_timestamp`` is within one expected update cadence.
    ``aging``
        Past one cadence but not yet past ``stale_after`` — the grace band
        that absorbs normal cycle jitter.  Not an error; a client that
        polls faster than the cadence sees this routinely.
    ``stale``
        Past ``stale_after`` while updates *were* expected.  This is the
        actionable state: the feed behind this endpoint is late.
    ``session_closed``
        A feed-backed endpoint whose feed is not due to produce anything
        right now (weekend, holiday, or a feed that only runs during the
        session).  The payload is the last good value — deliberately NOT
        reported as ``stale``, because an overnight consumer polling a
        closed market is not observing a fault and should not page on it.
    ``static``
        The endpoint is not feed-backed at all: completed history, or a
        result computed from the caller's own inputs.  Age here carries no
        health meaning and never becomes a fault.
    ``unknown``
        No source timestamp could be resolved from the payload (e.g. a
        pure calculator, an admin endpoint, or an empty result set).  A
        consumer should fall back to ``evaluated_at`` for endpoint health
        and make no claim about data age.
    """

    FRESH = "fresh"
    AGING = "aging"
    STALE = "stale"
    SESSION_CLOSED = "session_closed"
    STATIC = "static"
    UNKNOWN = "unknown"


# ---------------------------------------------------------------------------
# Cadence profiles
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CadenceProfile:
    """How often one class of endpoint is expected to produce new data.

    Cadence is session-dependent, which is exactly why
    ``market_session_status`` rides in the envelope: advertising "60 s" at
    03:00 on a Sunday would be a lie, and a consumer that alerted on it
    would page every weekend.

    ``closed_seconds`` is the cadence on a **weekday** outside the feed
    window (04:00–20:00 ET).  For anything derived from the market feed it
    is ``None``: ingestion stops when after-hours closes at 20:00 ET and
    resumes at 04:00, so no new observation can land in between and an
    ageing payload is the correct answer rather than a late one.  A
    non-``None`` value here means "this artifact really is still being
    produced overnight".  Weekends and NYSE holidays always resolve to "no
    updates expected" regardless of this field.

    ``stale_grace`` / ``stale_floor_seconds`` set how far past the cadence
    a payload may drift before it is called ``stale``.  Both exist because
    a pure multiplier is wrong at both ends of the range: 3x a 1 s cadence
    is too tight to survive one slow cycle, and 3x a 300 s cadence is
    needlessly loose.  ``stale_after`` = source + max(cadence x grace,
    floor).
    """

    name: str
    description: str
    regular_seconds: Optional[float]
    extended_seconds: Optional[float]
    closed_seconds: Optional[float]
    # False for classes that are not backed by a live feed at all (completed
    # history, caller-supplied calculators). They report ``static`` rather
    # than ``session_closed``: "this never goes stale" and "the market is
    # shut" are different facts and a consumer alerts on them differently.
    feed_backed: bool = True
    # True for artifacts produced once per trading session. Their age is
    # measured in SESSIONS, not wall-clock seconds: Friday's close is still
    # the correct answer all through Monday morning, and a flat wall-clock
    # window reported ``stale`` every Monday and after every holiday.
    session_scoped: bool = False
    stale_grace: float = 2.5
    stale_floor_seconds: float = 15.0

    def cadence_for(self, session: str, *, market_day: bool) -> Optional[float]:
        """Expected cadence in this session, or ``None`` if no updates are due.

        ``market_day`` is False on weekends and NYSE holidays; nothing
        upstream changes then, so every profile reports "no updates
        expected" and the status becomes ``session_closed``.
        """
        if not market_day:
            return None
        if session == SESSION_REGULAR:
            return self.regular_seconds
        if session in (SESSION_PRE_MARKET, SESSION_AFTER_HOURS):
            return self.extended_seconds
        return self.closed_seconds

    def stale_window(self, cadence_seconds: float) -> float:
        """Seconds past ``source_timestamp`` before the payload is stale."""
        return max(cadence_seconds * self.stale_grace, self.stale_floor_seconds)


# Cadences are read from the SAME config constants the engines run on, not
# copied from their defaults. An operator who retunes ANALYTICS_INTERVAL in
# .env would otherwise have the API keep advertising 60s while the engine
# ran on something else — publishing a cadence contract we then miss.
# The quote tape is POLLED every few seconds but STORED in one-minute buckets:
# _store_underlying floors each bar to bucket_timestamp(ts-1s,
# AGGREGATION_BUCKET_SECONDS) and overwrites the in-progress minute in place
# (src/ingestion/main_engine.py), and option_chains uses the same bucket. So the
# freshest row that can exist is 0-60s old, and grading against the 5s poll
# interval declared a healthy tape late for most of every minute — measured at
# fresh/aging/stale = 6/15/39 seconds per bucket, i.e. `stale` for 65% of the
# cash session on /api/market/quote, /api/option/* and open-interest.
#
# Cadence must describe the OBSERVATION granularity, not the collection rate.
REALTIME_QUOTE = CadenceProfile(
    name="realtime_quote",
    description=(
        "Underlying quote/bar tape and per-contract option quotes. Stored in "
        "config.AGGREGATION_BUCKET_SECONDS=60s buckets, so a new observation "
        "can appear at most once a minute however often ingestion polls."
    ),
    regular_seconds=float(AGGREGATION_BUCKET_SECONDS),
    extended_seconds=float(AGGREGATION_BUCKET_SECONDS),
    closed_seconds=None,
    stale_grace=2.5,
    # Two empty buckets. Extended-hours tape is thin enough that a minute with
    # no prints writes no row at all, which is not a fault.
    stale_floor_seconds=120.0,
)

# VIX/VXN are 5-minute bars (VOLATILITY_BAR_INTERVAL in
# src/ingestion/volatility_index_ingester.py), not the 1-minute tape, so they
# need their own profile — on the shared realtime_quote cadence they read
# `stale` for 91% of the session. Pinned to that constant by test.
VOLATILITY_BAR_SECONDS = 5 * 60

VOLATILITY_BAR = CadenceProfile(
    name="volatility_bar",
    description=(
        "CBOE volatility-index bars (VIX, VXN) on a 5-minute cadence. The "
        "in-progress bar is close-stamped in the future and is deliberately "
        "ignored, so the observation is the last COMPLETED boundary and is "
        "legitimately up to one full bar old."
    ),
    regular_seconds=float(VOLATILITY_BAR_SECONDS),
    extended_seconds=float(VOLATILITY_BAR_SECONDS),
    closed_seconds=None,
    stale_grace=2.0,
    stale_floor_seconds=float(2 * VOLATILITY_BAR_SECONDS),
)

ANALYTICS_CYCLE = CadenceProfile(
    name="analytics_cycle",
    description=(
        "Derived dealer-positioning analytics (GEX, walls, gamma flip, max "
        "pain, per-strike profile, vol/premium surfaces). Recomputed on the "
        "analytics cycle (config.ANALYTICS_INTERVAL=60s; "
        "ANALYTICS_OFF_HOURS_INTERVAL_SECONDS=300s off-hours)."
    ),
    regular_seconds=float(ANALYTICS_INTERVAL),
    extended_seconds=float(ANALYTICS_INTERVAL),
    # None, not the 300s off-hours cycle: the engine may still tick overnight
    # but option_chains/underlying_quotes stop at 20:00 ET, so every cycle
    # between 20:00 and 04:00 recomputes the SAME 20:00 observation. Claiming
    # a 300s cadence there made every analytics endpoint report `stale` for
    # eight hours a night — the false page this module exists to prevent.
    closed_seconds=None,
    stale_grace=2.5,
    stale_floor_seconds=60.0,
)

FLOW_AGGREGATE = CadenceProfile(
    name="flow_aggregate",
    description=(
        "Options-flow aggregates, bucketed to "
        "config.AGGREGATION_BUCKET_SECONDS=60s. No flow accrues outside the "
        "cash session, so the extended/closed cadences are unset."
    ),
    regular_seconds=float(AGGREGATION_BUCKET_SECONDS),
    extended_seconds=None,
    closed_seconds=None,
    stale_grace=2.5,
    stale_floor_seconds=60.0,
)

SIGNALS_CYCLE = CadenceProfile(
    name="signals_cycle",
    description=(
        "Signal-engine scores and events. The engine runs a 24x5 window "
        "(weekdays, non-holidays) on a ~1s loop "
        "(config.SIGNALS_INTERVAL=1), but a scored row only lands when its "
        "analytics inputs move, so the advertised cadence is deliberately "
        "conservative."
    ),
    # Deliberately NOT SIGNALS_INTERVAL (1s): the engine loops that fast but
    # a scored row only lands when its analytics inputs move, and advertising
    # a 1s cadence would report ``stale`` on a healthy quiet tape.
    regular_seconds=15.0,
    extended_seconds=60.0,
    # The signal engine runs 24x5, but a scored row can never carry an
    # observation newer than its inputs, and those stop with the feed at
    # 20:00 ET. Same reasoning as ANALYTICS_CYCLE.
    closed_seconds=None,
    stale_grace=3.0,
    stale_floor_seconds=60.0,
)

DAILY_CYCLE = CadenceProfile(
    name="daily_cycle",
    description=(
        "Once-per-session artifacts: the morning forecast, the scorecard, "
        "session closes and session levels. New rows land on the day's "
        "schedule, not on a polling loop."
    ),
    regular_seconds=86400.0,
    extended_seconds=86400.0,
    closed_seconds=86400.0,
    session_scoped=True,
    stale_grace=1.5,
    stale_floor_seconds=3600.0,
)

HISTORICAL = CadenceProfile(
    name="historical",
    description=(
        "Completed history (replay, backtest results, realized signal "
        "outcomes). Immutable once written — age is expected and is not a "
        "fault, so nothing here is ever reported stale."
    ),
    regular_seconds=None,
    extended_seconds=None,
    closed_seconds=None,
    feed_backed=False,
)

ON_DEMAND = CadenceProfile(
    name="on_demand",
    description=(
        "Computed fresh for each request from inputs supplied by the caller "
        "(calculators, what-if tools) or from process-local state (health, "
        "admin). There is no upstream feed to fall behind, so "
        "freshness_status reflects endpoint health only."
    ),
    regular_seconds=None,
    extended_seconds=None,
    closed_seconds=None,
    feed_backed=False,
)

CADENCE_PROFILES = {
    p.name: p
    for p in (
        REALTIME_QUOTE,
        VOLATILITY_BAR,
        ANALYTICS_CYCLE,
        FLOW_AGGREGATE,
        SIGNALS_CYCLE,
        DAILY_CYCLE,
        HISTORICAL,
        ON_DEMAND,
    )
}


# Path -> profile. Matched in order against the **v1 path** (the mirror
# strips the /api/v2 prefix before resolving), first glob wins, so the
# specific patterns are listed before the broad ones. Paths are matched
# with the literal ``{param}`` placeholders in them, not substituted values.
ENDPOINT_CADENCE: Tuple[Tuple[str, CadenceProfile], ...] = (
    # --- specific overrides, before their broader family ------------------
    ("/api/health*", ON_DEMAND),
    # Exact, not a glob: /api/gex/historical-context returns the LIVE headline
    # GEX metrics positioned against their rolling distributions, so a
    # `historical` classification reported `static` — never stale — on one of
    # the fourteen endpoints the documented public API product sells.
    ("/api/gex/historical", HISTORICAL),
    ("/api/market/historical*", HISTORICAL),
    ("/api/market/session-closes*", DAILY_CYCLE),
    ("/api/market/session-levels*", DAILY_CYCLE),
    # Ahead of the /api/market/* glob below: 5-minute bars, not the 1s tape.
    ("/api/market/volatility*", VOLATILITY_BAR),
    ("/api/max-pain/timeseries*", HISTORICAL),
    # Open positions are marked to market every engine cycle, so this is a
    # live view, not completed history. Under the trades* glob below it
    # reported `static` — "never a fault" — while the engine was dead.
    ("/api/signals/trades-live", SIGNALS_CYCLE),
    ("/api/signals/trades*", HISTORICAL),
    # The realised-outcome history hangs off the component name
    # (/api/signals/{signal_name}/events), so the old "/api/signals/events*"
    # pattern matched NOTHING and these fell through to the live signals
    # cadence — which grades sparse, triggered events on recency and calls a
    # quiet tape stale.
    ("/api/signals/*/events*", HISTORICAL),
    ("/api/tools/*", ON_DEMAND),
    # --- families ---------------------------------------------------------
    ("/api/v1/levels*", ANALYTICS_CYCLE),
    ("/api/levels*", ANALYTICS_CYCLE),
    ("/api/gex/*", ANALYTICS_CYCLE),
    ("/api/max-pain/*", ANALYTICS_CYCLE),
    ("/api/forced-flow/*", ANALYTICS_CYCLE),
    ("/api/technicals*", ANALYTICS_CYCLE),
    ("/api/flow/*", FLOW_AGGREGATE),
    ("/api/option/*", REALTIME_QUOTE),
    ("/api/market/*", REALTIME_QUOTE),
    ("/api/signals/*", SIGNALS_CYCLE),
    ("/api/forecast*", DAILY_CYCLE),
    ("/api/scorecard*", DAILY_CYCLE),
    ("/api/news*", DAILY_CYCLE),
    ("/api/replay/*", HISTORICAL),
    ("/api/backtest/*", HISTORICAL),
    ("/api/tradeworkz/*", SIGNALS_CYCLE),
    ("/api/admin/*", ON_DEMAND),
)

# Endpoints with no registry entry fall back to this. ON_DEMAND is the safe
# default: it makes no freshness claim it cannot support, so a newly added
# route is never mislabelled ``fresh``. A startup audit (see
# ``audit_cadence_coverage``) logs anything that lands here.
DEFAULT_PROFILE = ON_DEMAND


def resolve_profile(path: str) -> CadenceProfile:
    """Return the cadence profile registered for a **v1** API path."""
    for pattern, profile in ENDPOINT_CADENCE:
        if fnmatch.fnmatchcase(path, pattern):
            return profile
    return DEFAULT_PROFILE


def audit_cadence_coverage(paths: Iterable[str]) -> list[str]:
    """Return the paths that fell through to :data:`DEFAULT_PROFILE`.

    Called at startup by the v2 mirror so a route added without a registry
    entry shows up in the log instead of silently reporting ``unknown``
    freshness forever.
    """
    return [p for p in paths if not any(fnmatch.fnmatchcase(p, pat) for pat, _ in ENDPOINT_CADENCE)]


# ---------------------------------------------------------------------------
# Session resolution
# ---------------------------------------------------------------------------


def _calendar() -> Tuple[set, set, Any, Any, Any, Any]:
    """NYSE calendar + session boundaries, read through market_calendar.

    Imported lazily and defensively: a broken calendar must degrade the
    freshness verdict, never fail a response that already succeeded. The
    fallbacks are the normal-session boundaries, which is the conservative
    choice — it can only make us report a session as longer than it was.
    """
    try:
        from src.market_calendar import (
            NYSE_EXTENDED_END,
            NYSE_HALF_DAY_CLOSE,
            NYSE_HALF_DAY_EXTENDED_END,
            NYSE_HALF_DAYS,
            NYSE_HOLIDAYS,
            NYSE_REGULAR_CLOSE,
        )

        return (
            NYSE_HOLIDAYS,
            NYSE_HALF_DAYS,
            NYSE_REGULAR_CLOSE,
            NYSE_HALF_DAY_CLOSE,
            NYSE_EXTENDED_END,
            NYSE_HALF_DAY_EXTENDED_END,
        )
    except Exception:  # noqa: BLE001 - never fail a response over the calendar
        logger.warning("freshness: NYSE calendar unavailable", exc_info=True)
        return set(), set(), _at(16, 0), _at(13, 0), _at(20, 0), _at(17, 0)


def _is_market_day(d: date) -> bool:
    holidays, _, _, _, _, _ = _calendar()
    return d.weekday() < 5 and d not in holidays


def session_close_for(d: date) -> Any:
    """The ET regular-session close on ``d`` — 13:00 on an early-close day."""
    _, half_days, regular, half, _, _ = _calendar()
    return half if d in half_days else regular


def _is_futures(symbol: Optional[str]) -> bool:
    """True when ``symbol`` is a first-class future (ES/NQ)."""
    if not symbol:
        return False
    try:
        from src.symbols import is_futures_symbol

        return bool(is_futures_symbol(symbol))
    except Exception:  # noqa: BLE001 - never fail a response over symbol lookup
        return False


def futures_context(now: Optional[datetime] = None) -> Tuple[str, bool]:
    """``(market_session_status, market_day)`` on the CME calendar.

    ES and NQ are served natively from ``futures_quotes`` and trade Sun 18:00
    to Fri 17:00 ET, minus the daily maintenance break — roughly 23 hours a
    day. Grading them on the NYSE cash calendar made the envelope report
    ``session_closed`` for every hour CME trades and NYSE does not, so a dead
    overnight futures feed was invisible: the v1 body said
    ``stale: true, data_age_seconds: 2701`` while the v2 envelope beside it
    said no update was due. A monitor built on the envelope — the thing v2
    exists to sell — stayed silent through the whole outage.

    ``is_futures_session_open`` is the same helper the quote endpoint already
    uses to label the payload's own ``session`` field, so the two can no
    longer disagree.
    """
    try:
        from src.market_calendar import is_futures_session_open

        live = is_futures_session_open(now)
    except Exception:  # noqa: BLE001
        logger.warning("freshness: futures calendar unavailable", exc_info=True)
        return market_context(now)
    # The CME session has no pre/after-hours split; it is open or it is not.
    return (SESSION_REGULAR, True) if live else (SESSION_CLOSED, False)


def market_context(now: Optional[datetime] = None) -> Tuple[str, bool]:
    """Return ``(market_session_status, market_day)`` for ``now``.

    ``market_day`` is False on weekends and NYSE holidays — the days on
    which no profile expects an update, whatever its ``closed_seconds``.

    Early-close days are honoured: on a half day the regular session ends
    at 13:00 ET and the extended feed at 17:00, so the 13:00–16:00 window
    reports ``after-hours`` rather than pricing a 5-second quote cadence
    against a tape that stopped three hours ago.
    """
    now_et = (now or datetime.now(timezone.utc)).astimezone(_ET)
    today = now_et.date()
    _, half_days, regular_close, half_close, ext_end, half_ext_end = _calendar()
    market_day = _is_market_day(today)
    if not market_day:
        return SESSION_CLOSED, False

    is_half = today in half_days
    close_t = half_close if is_half else regular_close
    ext_t = half_ext_end if is_half else ext_end

    t = now_et.time()
    if t < _at(4, 0):
        return SESSION_CLOSED, True
    if t < _at(9, 30):
        return SESSION_PRE_MARKET, True
    if t < close_t:
        return SESSION_REGULAR, True
    if t < ext_t:
        return SESSION_AFTER_HOURS, True
    return SESSION_CLOSED, True


def feed_window_open(profile: CadenceProfile, now: datetime) -> Optional[datetime]:
    """The instant the CURRENT feed window opened, for ``now``.

    ``stale_after`` was computed purely as ``source_timestamp + window``. Across
    a feed-window boundary that anchor sits in the PREVIOUS window and is
    already hours old, so the moment ``cadence_for`` starts returning a number
    the payload is instantly past its threshold: at 04:00:00 ET the newest
    observation is still the prior evening's 19:59 bar, and every feed-backed
    endpoint flipped ``session_closed -> stale`` in one second with the whole
    ``aging`` grace band unreachable. The grace mechanism was structurally dead
    exactly where it was designed to apply.

    Anchoring to ``max(source_timestamp, window_open)`` gives a payload one
    second into a new window a full grace period before it is called late,
    which is the honest reading: nothing can be late yet, because nothing has
    had time to arrive.

    Cash-session-only profiles (``extended_seconds is None`` — flow accrues
    only 09:30-16:00) open at 09:30 ET; everything else opens with ingestion
    at 04:00 ET. Returns ``None`` when the profile expects nothing.
    """
    if profile.regular_seconds is None:
        return None
    now_et = now.astimezone(_ET)
    open_t = _at(9, 30) if profile.extended_seconds is None else _at(4, 0)
    if now_et.time() < open_t:
        return None
    return _ET.localize(
        datetime(now_et.year, now_et.month, now_et.day, open_t.hour, open_t.minute)
    ).astimezone(timezone.utc)


def next_session_close_after(dt: datetime) -> datetime:
    """The close of the first trading session strictly after ``dt``'s date.

    Used to age once-per-session artifacts in trading days rather than
    wall-clock seconds.  A Friday close is not late on Monday morning — the
    next one is not due until Monday's close — and a flat 36-hour window
    made every ``daily_cycle`` endpoint read ``stale`` every Monday and
    after every holiday.
    """
    d = dt.astimezone(_ET).date()
    # Bounded: a calendar that somehow marks 10 consecutive days non-trading
    # falls back to the last candidate rather than looping forever.
    for _ in range(10):
        d = d + timedelta(days=1)
        if _is_market_day(d):
            break
    close_t = session_close_for(d)
    return _ET.localize(datetime(d.year, d.month, d.day, close_t.hour, close_t.minute)).astimezone(
        timezone.utc
    )


def _at(hour: int, minute: int):
    from datetime import time as _time

    return _time(hour, minute)


# ---------------------------------------------------------------------------
# Timestamp extraction
# ---------------------------------------------------------------------------

# Keys that carry the instant a snapshot/computation was PRODUCED.
_GENERATED_KEYS = ("generated_at", "evaluated_at", "as_of", "snapshot_time", "computed_at")

# Keys that carry the instant of the UPSTREAM market observation. These are
# the only keys freshness is graded against when any of them is present.
_SOURCE_KEYS = (
    "source_timestamp",
    # Ranked/top-N responses expose this so freshness is graded on the feed's
    # recency rather than on which selected row happens to be newest. It is
    # always >= any row timestamp, so the max() below picks it up naturally.
    "session_latest_at",
    # Response-level "when was this view last refreshed", for payloads whose
    # rows carry only an ENTRY or selection instant. /api/signals/trades-live
    # is the case: its rows are stamped when the position opened, so a
    # position held since the open read hours stale on a healthy engine.
    # Same max() precedence — a refresh is never older than what it refreshed.
    "last_refreshed_at",
    "timestamp",
    "quote_timestamp",
    "signal_timestamp",
    "interval_timestamp",
    "bar_timestamp",
    "realized_at",
)

# Deliberately NOT a source key: ``last_data_update`` is /api/health's own
# REPORT about data freshness, not a timestamp OF the health payload. Treating
# another endpoint's freshness report as our observation is a category error,
# and it produced a wrong answer on the one endpoint whose job is reporting
# data age: /api/v2/health carried a three-hour-old quote stamp and graded it
# `static` — "this never goes stale" — because health is an on-demand,
# non-feed-backed profile. It now reports `unknown`, which is the honest
# answer: the endpoint makes no freshness claim of its own, and its body's
# `data_age_seconds` remains the signal to read.

# Row-bookkeeping keys: when the row was WRITTEN, which is not when the market
# was observed. option_chains rows are UPSERTed in 60-second buckets with
# ``updated_at = NOW()`` on conflict (see src/api/database.py and
# src/ingestion/main_engine.py), so a re-write of an OLD snapshot bumps
# updated_at to now. Ranking these alongside the observation keys let a
# 10-minute-stale chain report age_seconds=3.0 and ``fresh``.
#
# They are a fallback tier, consulted only when the payload carries no real
# observation key anywhere — better than reporting ``unknown`` for a table
# that only tracks write time, but never allowed to outrank a real stamp.
_BOOKKEEPING_KEYS = (
    "last_update",
    "updated_at",
    "created_at",
)

# Forward-looking or unrelated stamps that must never be mistaken for an
# observation: a forecast's target time is in the future, an expiration is a
# contract property, and stale_after is our own output.
_EXCLUDED_KEYS = frozenset(
    {
        "target_at",
        "stale_after",
        "expiration",
        "expiration_date",
        "expires_at",
        "expiry",
        "settlement_time",
        "next_update_at",
        "tracking_started_at",
        "start_time",
        "start_date",
        "end_date",
        "session_date",
        "trade_date",
    }
)

# Bounds on the payload walk. /api/flow/by-contract can return hundreds of
# thousands of rows for a full session; a naive full-tree scan would put real
# CPU on the hot path. Lists are sampled at both ends because every
# time-bearing collection in this API is time-ordered, so the newest row is
# at one end or the other.
_MAX_DEPTH = 6
_LIST_SAMPLE = 50
# Hard ceiling on nodes visited. Depth and width bounds alone are NOT a bound:
# they multiply. /api/gex/strike-profile-timeseries returns 78 buckets each
# holding ~300 strikes, so a depth-first walk descended 7,800 strike dicts —
# none of which carries a timestamp — for ~9 ms of pure CPU per request on an
# endpoint the rewind chart polls at ~1 Hz.
_MAX_NODES = 2000

# A ``generated_at`` closer than this to the evaluation instant was minted
# while building the response, so it says nothing about the data's age. One
# second is comfortably above realistic handler latency and far below any
# genuine compute cycle (the fastest here is the 5s quote poll).
_REQUEST_TIME_STAMP_SECONDS = 1.0


def _coerce_datetime(value: Any) -> Optional[datetime]:
    """Best-effort parse of a payload value into an aware UTC datetime."""
    if isinstance(value, datetime):
        dt = value
    elif isinstance(value, str):
        raw = value.strip()
        if not raw or len(raw) < 10 or len(raw) > 40:
            return None
        try:
            dt = datetime.fromisoformat(raw.replace("Z", "+00:00"))
        except ValueError:
            return None
    else:
        # Bare dates and epoch numbers are deliberately not treated as
        # observation instants: a date has no time-of-day to age against,
        # and an unlabelled number is as likely to be a price as a stamp.
        return None
    if dt.tzinfo is None:
        # Naive stamps come off the DB in UTC (all writers use timezone-aware
        # UTC or UTC-normalised columns); assuming ET here would shift every
        # age by hours.
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc)


def _scan_timestamps(payload: Any, now: datetime) -> Tuple[Optional[datetime], Optional[datetime]]:
    """Walk ``payload`` and return ``(generated_at, latest_event_at)``.

    The walk is **breadth-first**, which is what makes the node ceiling safe
    to enforce.  Every timestamp in this API's payloads lives at or near the
    top of its object — a row's own stamp sits beside its data, not under
    three more levels of nesting — so visiting level by level finds all of
    them before descending into the wide, stamp-free leaf collections
    (per-strike rows, per-contract quotes) that dominate the node count.
    A depth-first walk with the same ceiling would spend the entire budget
    inside the first row's children and miss the later rows' stamps, which
    would silently change ``latest_event_at``.

    Breadth-first also makes the "shallowest wins" rule for ``generated_at``
    fall out of the traversal order instead of needing to be tracked.

    Bounded three ways: ``_MAX_DEPTH`` (levels), ``_LIST_SAMPLE`` (head and
    tail of each collection, since every time-bearing collection here is
    time-ordered) and ``_MAX_NODES`` (total). Future-dated values are
    ignored — they are forecast targets or contract properties, never
    observations.
    """
    generated: Optional[datetime] = None
    generated_depth = _MAX_DEPTH + 1
    latest: Optional[datetime] = None
    bookkeeping: Optional[datetime] = None
    # Small tolerance for clock skew between the DB writer and this process;
    # without it a stamp a few hundred ms in the future is silently dropped.
    horizon = now + timedelta(seconds=5)

    queue: Deque[Tuple[Any, int]] = deque(((payload, 0),))
    budget = _MAX_NODES
    current_depth = 0

    while queue and budget > 0:
        node, depth = queue.popleft()
        # A level boundary. Stop as soon as a completed level has yielded an
        # observation stamp: these payloads carry their stamps at ONE level
        # (a row's stamp sits beside its data), and everything below that is
        # leaf detail — per-strike gamma, per-contract quotes — that costs
        # thousands of nodes and can contribute nothing. This is what turns
        # the walk from "bounded by a big ceiling" into "cheap on real
        # payloads": strike-profile-timeseries now stops after ~80 nodes
        # instead of grinding through 7,800 strike dicts.
        if depth != current_depth:
            if latest is not None:
                break
            current_depth = depth
        budget -= 1
        if depth > _MAX_DEPTH:
            continue

        if isinstance(node, (list, tuple)):
            # Index into the sequence rather than slicing it: a 500k-row body
            # would otherwise be copied in full just to read 100 elements.
            size = len(node)
            if size > 2 * _LIST_SAMPLE:
                indices: Iterable[int] = chain(
                    range(_LIST_SAMPLE), range(size - _LIST_SAMPLE, size)
                )
            else:
                indices = range(size)
            for i in indices:
                item = node[i]
                if isinstance(item, (dict, list, tuple, BaseModel)):
                    queue.append((item, depth + 1))
            continue

        if isinstance(node, dict):
            items: Iterable[Tuple[Any, Any]] = node.items()
        elif isinstance(node, BaseModel):
            items = node.__dict__.items()
        else:
            continue

        for key, value in items:
            if isinstance(value, (dict, list, tuple, BaseModel)):
                queue.append((value, depth + 1))
                continue
            if not isinstance(key, str) or key in _EXCLUDED_KEYS:
                continue
            if (
                key not in _GENERATED_KEYS
                and key not in _SOURCE_KEYS
                and key not in _BOOKKEEPING_KEYS
            ):
                continue
            dt = _coerce_datetime(value)
            if dt is None or dt > horizon:
                continue
            if key in _BOOKKEEPING_KEYS:
                bookkeeping = dt if bookkeeping is None else max(bookkeeping, dt)
            elif key in _GENERATED_KEYS:
                # Breadth-first, so the first level to yield a generated stamp
                # is the shallowest: a nested row's own ``as_of`` describes
                # that row, while the top-level one describes the response.
                # Ties at the same depth take the newest.
                if depth < generated_depth:
                    generated, generated_depth = dt, depth
                elif depth == generated_depth and generated is not None:
                    generated = max(generated, dt)
            else:
                latest = dt if latest is None else max(latest, dt)

    # Only fall back to write-time bookkeeping when nothing observed a market.
    return generated, (latest if latest is not None else bookkeeping)


# ---------------------------------------------------------------------------
# The envelope
# ---------------------------------------------------------------------------


class Freshness(BaseModel):
    """The v2 freshness envelope. Present on every ``/api/v2/*`` response."""

    evaluated_at: datetime = Field(
        description=(
            "When the API evaluated this response (server wall clock, UTC). "
            "Endpoint-health signal: advances on every request even when the "
            "underlying data is unchanged."
        )
    )
    generated_at: datetime = Field(
        description=(
            "When the served data was computed. Equals the snapshot stamp for "
            "cycle-backed endpoints, or evaluated_at for endpoints computed on "
            "demand for this request."
        )
    )
    source_timestamp: Optional[datetime] = Field(
        default=None,
        description=(
            "Timestamp of the upstream market observation the payload derives "
            "from. This is what freshness_status is measured against. Null "
            "when the endpoint has no upstream feed or returned no rows."
        ),
    )
    latest_event_at: Optional[datetime] = Field(
        default=None,
        description=(
            "Newest event timestamp present in the payload (last bar, last "
            "trade, last scored row). Best-effort on very large responses, "
            "which are sampled rather than fully walked."
        ),
    )
    age_seconds: Optional[float] = Field(
        default=None,
        description=(
            "evaluated_at - source_timestamp, in seconds. Null when " "source_timestamp is null."
        ),
    )
    market_session_status: str = Field(
        description="pre-market | regular | after-hours | closed (US/Eastern)."
    )
    expected_update_cadence: Optional[str] = Field(
        default=None,
        description=(
            "ISO-8601 duration for how often this endpoint's data is expected "
            "to change right now, e.g. PT60S. Null means no updates are "
            "expected (weekend, holiday, or a feed that only runs during the "
            "session)."
        ),
    )
    expected_update_cadence_seconds: Optional[float] = Field(
        default=None,
        description="expected_update_cadence as a number of seconds.",
    )
    cadence_profile: str = Field(
        description=(
            "Identifier of the cadence class this endpoint belongs to, e.g. "
            "analytics_cycle. Stable across releases; the seconds behind it "
            "may be retuned."
        )
    )
    stale_after: Optional[datetime] = Field(
        default=None,
        description=(
            "Instant after which this payload should be treated as stale. "
            "Null whenever expected_update_cadence is null."
        ),
    )
    freshness_status: FreshnessStatus = Field(
        description="fresh | aging | stale | session_closed | static | unknown."
    )


DataT = TypeVar("DataT")


class Envelope(BaseModel, Generic[DataT]):
    """``{"data": <v1 payload>, "freshness": {...}}`` — the v2 response shape.

    ``data`` is byte-for-byte the v1 payload, including whatever event
    timestamps it already carried.  The envelope adds a parallel view; it
    never rewrites or removes a field, so migrating from v1 to v2 is
    "unwrap ``data``" and nothing else.
    """

    data: DataT
    freshness: Freshness


def _iso_duration(seconds: float) -> str:
    """Render seconds as an ISO-8601 duration (``PT60S`` / ``PT1H``).

    Whole hours and minutes are rendered as such because that is what a
    human reads in the docs; anything else stays in seconds rather than
    inventing a mixed representation.
    """
    if seconds >= 3600 and seconds % 3600 == 0:
        return f"PT{int(seconds // 3600)}H"
    if seconds >= 60 and seconds % 60 == 0:
        return f"PT{int(seconds // 60)}M"
    if seconds == int(seconds):
        return f"PT{int(seconds)}S"
    return f"PT{seconds:g}S"


def build_freshness(
    payload: Any,
    *,
    profile: CadenceProfile,
    now: Optional[datetime] = None,
    symbol: Optional[str] = None,
) -> Freshness:
    """Compute the freshness envelope for one response payload.

    Never raises: a freshness block is metadata about a response that has
    already been produced, so a failure to characterise it must not turn a
    good 200 into a 500.  Anything unexpected degrades to
    ``FreshnessStatus.UNKNOWN``.
    """
    evaluated_at = now or datetime.now(timezone.utc)
    # ES/NQ keep their own calendar; everything else is graded on NYSE cash.
    if _is_futures(symbol):
        session, market_day = futures_context(evaluated_at)
    else:
        session, market_day = market_context(evaluated_at)

    try:
        generated_at, latest_event_at = _scan_timestamps(payload, evaluated_at)
    except Exception:  # noqa: BLE001 - metadata must never break the response
        logger.warning("freshness: payload scan failed", exc_info=True)
        generated_at, latest_event_at = None, None

    # source_timestamp is the upstream observation. When a payload carries only
    # a computation stamp (a snapshot with no row-level stamps) that stamp is
    # the best available proxy — but ONLY if it describes an earlier
    # computation. A handler that stamps datetime.now() as it builds the
    # response (e.g. /api/news/headlines) would otherwise report age_seconds
    # ~0 and `fresh` forever, including during a total upstream outage that
    # returned zero items. A stamp minted during this request measures the
    # request, not the data, so it is not evidence of freshness.
    source_timestamp = latest_event_at
    if source_timestamp is None and generated_at is not None:
        minted_now = (evaluated_at - generated_at).total_seconds() < _REQUEST_TIME_STAMP_SECONDS
        source_timestamp = None if minted_now else generated_at
    age_seconds = (
        round((evaluated_at - source_timestamp).total_seconds(), 3) if source_timestamp else None
    )

    cadence_seconds = profile.cadence_for(session, market_day=market_day)
    stale_after: Optional[datetime] = None
    if cadence_seconds is not None and source_timestamp is not None:
        if profile.session_scoped:
            # Due when the NEXT trading session's artifact should exist, plus
            # the grace floor — so a Friday artifact is not "late" until well
            # after Monday's close.
            stale_after = next_session_close_after(source_timestamp) + timedelta(
                seconds=profile.stale_floor_seconds
            )
        else:
            # Never start the clock before the window that could produce the
            # next observation actually opened (see feed_window_open).
            window_open = feed_window_open(profile, evaluated_at)
            anchor = source_timestamp
            if window_open is not None and window_open > anchor:
                anchor = window_open
            stale_after = anchor + timedelta(seconds=profile.stale_window(cadence_seconds))

    if source_timestamp is None:
        status = FreshnessStatus.UNKNOWN
    elif cadence_seconds is None:
        # No update was due, so an old value is correct rather than late.
        status = FreshnessStatus.SESSION_CLOSED if profile.feed_backed else FreshnessStatus.STATIC
    elif profile.session_scoped:
        # Session-scoped artifacts are fresh right up to their stale_after;
        # there is no meaningful "aging" band between two daily deliveries.
        status = (
            FreshnessStatus.FRESH
            if stale_after is not None and evaluated_at <= stale_after
            else FreshnessStatus.STALE
        )
    elif age_seconds is not None and age_seconds <= cadence_seconds:
        status = FreshnessStatus.FRESH
    elif stale_after is not None and evaluated_at <= stale_after:
        status = FreshnessStatus.AGING
    else:
        status = FreshnessStatus.STALE

    return Freshness(
        evaluated_at=evaluated_at,
        # An endpoint that computes its answer for this request has no
        # separate generation instant — the evaluation IS the generation.
        generated_at=generated_at or evaluated_at,
        source_timestamp=source_timestamp,
        latest_event_at=latest_event_at,
        age_seconds=age_seconds,
        market_session_status=session,
        expected_update_cadence=(
            _iso_duration(cadence_seconds) if cadence_seconds is not None else None
        ),
        expected_update_cadence_seconds=cadence_seconds,
        cadence_profile=profile.name,
        stale_after=stale_after,
        freshness_status=status,
    )
